<a href="https://colab.research.google.com/github/shinjangwoon/jangwoonshin/blob/practice/numpy%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
print(np.__version__)
# ndarray 생성
data = [10, 20, 30]
arr = np.array(data) # 입력된 데이터(object)를 인자로 받아 ndarray를 생성하는 함수
print('\nCreate 1D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}"
.format(arr.shape, arr.size, arr.dtype, arr.ndim ))


1.19.5

Create 1D Array
[10 20 30]
type =  <class 'numpy.ndarray'>
shape: (3,), size: 3, dtype: int64, dimension: 1


In [ ]:
import numpy as np
# 2차원 ndarray 생성
data = [[1,2,3], [4,5,6]]
arr = np.array(data, dtype=float) # float 타입 변경 
print('\nCreate 2D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}"
.format(arr.shape, arr.size, arr.dtype, arr.ndim ))



Create 2D Array
[[1. 2. 3.]
 [4. 5. 6.]]
type =  <class 'numpy.ndarray'>
shape: (2, 3), size: 6, dtype: float64, dimension: 2


In [ ]:
# 3차원 ndarray 생성
data = [[[1, 2, 3],
         [4, 5, 6]],
        [[3, 2, 1],
         [4, 5, 6]]]
arr = np.array(data, dtype=float)
print('\nCreate 3D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}"
.format(arr.shape, arr.size, arr.dtype, arr.ndim))


Create 3D Array
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [4 5 6]]]
type =  <class 'numpy.ndarray'>
shape: (2, 2, 3), size: 12, dtype: int64, dimension: 3
